### ISSUE TITLE
Rename to sourcegraph-discussions

### ISSUE THREAD

**Issue by sqs** [sourcegraph/sourcegraph-discussions#2]
Other extensions (sourcegraph-{codecov,basic-code-intel,hello-world,logdna,lightstep}) don’t have the “-extension” in their name. And VS Code/Atom/Sublime extensions are usually just $EDITOR-whatever. 

Curious: what made you want to include “-extension”?

**Comment by slimsag** [comment]
I named it this way because I was afraid that e.g. Google searches would leave people to believe that _this_ is Sourcegraph Code Discussions, when in reality there is a whole different aspect to it.

However, this is all too confusing from a user POV. I am going to make this repository (and the extension page on Sourcegraph) the primary entry-point for users who are interested in Code Discussions, so we don't have to worry about this any further :)

Repository renamed.
